---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drpc
spec:
  preferredCluster: prsurve-c1-7j
  drPolicyRef:
    name: drpolicy-5m
  placementRef:
    kind: Placement
    name: placement
  pvcSelector:
    matchLabels:
      appname: busybox
