---
resources:
  - ../../base/cg
patches:
  # Customize for internal cephfs storage.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-cg1-pvc1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-cephfs 
        # rook-cephfs-fs1
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
  - target:
      kind: PersistentVolumeClaim
      name: busybox-cg1-pvc2
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-cephfs 
        # rook-cephfs-fs1
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
  - target:
      kind: PersistentVolumeClaim
      name: busybox-cg1-pvc3
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-cephfs 
        # rook-cephfs-fs1
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
