---
resources:
  - channel.yaml
  - namespace.yaml
patches:
  # Customize path to application.
  - target:
      kind: Channel
      name: ramen-gitops
    patch: |-
      - op: replace
        path: /spec/pathname
        value: https://github.com/kumarsgoyal/ocm-ramen-samples.git
