---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc1
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs-fs1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc2
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs-fs1
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: busybox-cg1-pvc3
# spec:
#   accessModes:
#     - ReadWriteMany
#   # Customize in your overlay.
#   storageClassName: rook-cephfs-fs1
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc4
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs-fs1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc5
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs-fs1
  resources:
    requests:
      storage: 1Gi