---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
spec:
  clusterIP: None
  selector:
    app: busybox
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  serviceName: busybox-service
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: docker.io/kumarsgoyal/cg-manager:latest
        command: ["/bin/sh", "-c", "/app/log-replica"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: LOG_FILE_PATH
          value: "/app/data/log.yaml" 
        - name: COUNTER_FILE_PATH
          value: "/app/data/counter-%d.yaml" 
        - name: TIME_INTERVAL
          value: "3000"
        - name: TIMEOUT
          value: "5000"
        - name: PORT
          value: ":8080"
        - name: SERVICE_ADDR
          value: "busybox-%d.busybox-service.deployment-cg-cephfs.svc.cluster.local:8080"  # headless service name for replicas  
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLICA_COUNT
          value: "3"  
        volumeMounts:
        - name: busybox-volume
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: busybox-volume 
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi  
      storageClassName: rook-cephfs-fs1  
