---
resources:
  - ../../base
namespace: deployment-cg-cephfs
commonLabels:
  app: deployment-cg-cephfs
patches:
  # Customize path to application.
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/deployment/base/cg
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-branch
        value: cg-cephfs-minikube-local
